name: ems_mobile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.18.0
  accordion: ^2.5.1
  dio: ^5.1.1
  animated_splash_screen: ^1.3.0
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  awesome_snackbar_content: ^0.1.1
  jwt_decode: ^0.3.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_zoom_drawer: ^3.0.4+1
  flutter_native_splash: ^2.2.19
  liquid_progress_indicator: ^0.4.0
  file_picker: ^5.2.10
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/ems_logo_mini.png
  android: true
  ios: true
